data:
    name: 'sfm'
    sequences: [
        'british_museum', 'florence_cathedral_side',
        'lincoln_memorial_statue', 'london_bridge',
        'milan_cathedral', 'mount_rushmore',
        'piazza_san_marco', 'reichstag', 'sagrada_familia',
        'st_pauls_cathedral', 'united_states_capitol']
    preprocessing:
        grayscale: true
model:
    name: 'hf_net'
    image_channels: 1
    local:
        detector_threshold: 0.005
