data:
    name: 'distillation'
    image_dirs: ['google_landmarks/images', 'bdd/dawn_images_vga',
                 'bdd/night_images_vga']
    load_targets: True
    targets:
        - dir: 'global_descriptors'
          keys: ['global_descriptor']
    truncate: [185000, null, null]
    preprocessing:
        grayscale: true
    validation_size: 192
    cache_in_memory: false
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {delta_range: [-75., 40.]}
                random_contrast: {strength_range: [0.3, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                    prob: 0.5
                motion_blur: {kernel_size: [13, 21], prob: 0.1}
model:
    name: 'mobilenetvlad'
    image_channels: 1
    dropout_keep_prob: null
    intermediate_proj: 0
    dimensionality_reduction: 4096
    depth_multiplier: 0.75
    n_clusters: 32
    train_backbone: true
    batch_size: 16
    eval_batch_size: 16
    learning_rate: [0.001, 0.0001, 0.00001, 0.000001]
    learning_rate_step: [40000, 60000, 70000]
weights: 'mobilenet_v2_0.75_224/mobilenet_v2_0.75_224.ckpt'
train_iter: 150000
validation_interval: 500
save_interval: 5000
keep_checkpoints: 100
