data:
    name: 'distillation'
    image_dirs: ['google_landmarks/images',
                 'bdd/dawn_images_vga', 'bdd/night_images_vga']
    shuffle: false
    preprocessing:
        resize: [480, 640]
        grayscale: false
model:
    name: 'netvlad_original'
    image_channels: 3
weights: 'vd16_pitts30k_conv5_3_vlad_preL2_intra_white/vd16_pitts30k_conv5_3_vlad_preL2_intra_white'
