data:
    name: 'cmu'
    sequences: ['slice2', 'slice3', 'slice4', 'slice5', 'slice6', 'slice7',
                'slice8', 'slice9', 'slice10', 'slice17']
    grayscale: false
    load_db: true
    load_queries: true
    resize_max: 1024
model:
    name: 'netvlad_original'
    local_descriptor_layer: 'conv3_3'
    image_channels: 3
weights: 'vd16_pitts30k_conv5_3_vlad_preL2_intra_white/vd16_pitts30k_conv5_3_vlad_preL2_intra_white'
