data:
    name: 'nclt'
    test_sequences: ['2012-01-08', '2012-08-20', '2013-02-23']
    camera: 4
model:
    name: 'netvlad_original'
    image_channels: 1
weights: 'vd16_pitts30k_conv5_3_vlad_preL2_intra_white/vd16_pitts30k_conv5_3_vlad_preL2_intra_white'
