data:
    name: 'robotcar'
    sequences: ['overcast-reference']
    resize_max: 960
model:
    name: 'super_point_pytorch'
    nms_radius: 0
    detector_threshold: 0.005
    image_channels: 1
weights: 'superpoint_v1.pth'
